title: Catatan Kurator Musixmatch
description: Catatan kurator Indonesia
theme: just-the-docs

url: https://curators-id.github.io/panduan

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
