title: Kurator Indonesia Musixmatch
description: Catatan untuk kurator Indonesia
theme: just-the-docs

url: https://curators-id.github.io/panduan

aux_links:
  Template Repository: https://github.com/curators-id/panduan

callouts:
  important:
    title: Warning
    color: yellow
